# Generated by Django 5.1.6 on 2025-04-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_image_hash_vehicle_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Kerala', max_length=255),
            preserve_default=False,
        ),
    ]
